import { chat } from './ai-client';
import { 
  AGENTS_MD_PROMPT, 
  BOB_MODE_PROMPT, 
  CURSORRULES_PROMPT, 
  CLAUDE_MD_PROMPT, 
  COPILOT_INSTRUCTIONS_PROMPT 
} from './prompts';
import { RepoMeta, GeneratedFiles } from '../types';

function extractCodeContext(keyFiles: Record<string, string>, fileTree: string[]): string {
  let context = '';
  
  // File tree summary (top 50)
  context += `## File Tree (${fileTree.length} total files)\n`;
  context += fileTree.slice(0, 50).join('\n') + '\n\n';
  
  // Detect language distribution
  const extCounts: Record<string, number> = {};
  for (const f of fileTree) {
    const ext = f.split('.').pop() || 'unknown';
    extCounts[ext] = (extCounts[ext] || 0) + 1;
  }
  context += `## Language Distribution\n`;
  for (const [ext, count] of Object.entries(extCounts).sort((a, b) => b[1] - a[1]).slice(0, 10)) {
    context += `- .${ext}: ${count} files\n`;
  }
  context += '\n';
  
  // Key file excerpts (first 80 lines each)
  for (const [path, content] of Object.entries(keyFiles)) {
    const lines = content.split('\n').slice(0, 80);
    context += `## File: ${path}\n\`\`\`\n${lines.join('\n')}\n\`\`\`\n\n`;
  }
  
  return context;
}

export async function generateContextFiles(
  analysis: any, 
  tribalRules: string[], 
  meta: RepoMeta,
  keyFiles: Record<string, string>,
  fileTree: string[]
): Promise<GeneratedFiles> {
  const analysisStr = JSON.stringify(analysis, null, 2);
  const tribalStr = tribalRules.length > 0 
    ? tribalRules.map((r, i) => `${i + 1}. ${r}`).join('\n')
    : 'No explicit tribal rules found in PR logs. Relying on default framework guidelines.';

  // Helper function to query Granite for a file content with safe fallbacks
  async function generateFile(promptTemplate: string, fallbackContent: string): Promise<string> {
    try {
      const codeContext = extractCodeContext(keyFiles, fileTree);
      const system = "You are a professional software architect. Your goal is to output ONLY the requested file contents without any codeblocks, markdown wrapper tags, or conversational fluff.";
      const user = promptTemplate
        .replace('{analysisJson}', analysisStr)
        .replace('{tribalRules}', tribalStr)
        .replace('{codeContext}', codeContext)
        .replace('{project_name}', meta.name);
      
      const response = await chat(system, user);
      if (response && response.trim().length > 200) {
        return response.trim();
      }
      return fallbackContent;
    } catch (err) {
      console.warn('Error generating file with Granite, falling back to template:', err);
      return fallbackContent;
    }
  }

  // Pre-generate professional templates for fallbacks
  const framework = analysis.buildDeploy?.framework || 'Next.js';
  const naming = analysis.conventions?.namingPattern || 'camelCase';
  const buildCmd = analysis.buildDeploy?.buildCommand || 'npm run build';
  const testCmd = analysis.buildDeploy?.testCommand || 'npm run test';
  const pattern = analysis.architecture?.pattern || 'Layered';
  const timestamp = new Date().toLocaleDateString();
  const score = analysis.conventions?.score || 45;
  const projected = Math.min(98, score + 40);

  const defaultAgentsMd = `# AGENTS.md — Generated by AgentIQ 🧠
# AgentIQ Score: ${score}/100 → ${projected}/100 (projected after sync)
# Generated: ${timestamp}

## 🚀 Project Identity
**${meta.name}** — ${meta.description || 'A software codebase'}
- **Primary Language:** ${meta.language || 'TypeScript'}
- **Stars:** ${meta.stars || 0} | **Forks:** ${meta.forks || 0}
- **File Count:** ${meta.fileCount || fileTree.length}

## 🛠️ Tech Stack
| Layer | Technology |
|-------|-----------|
| Framework | ${framework} |
| Language | TypeScript / JavaScript |
| Package Manager | npm |

## 🏗️ Architecture
- **Pattern:** ${pattern}
- **Organization:** ${analysis.conventions?.fileOrganization || 'Standard modern project layout'}

## 📝 Naming Convention Bible
| Entity | Convention | Example |
|--------|-----------|---------|
| Variables | ${naming} | userData, isLoading |
| Functions | ${naming} | fetchUser, handleSubmit |
| Components | PascalCase | DashboardLayout |
| Files (utils) | kebab-case | ai-client.ts |
| CSS Classes | kebab-case | glass-interactive |

### ❌ Anti-Patterns
- Do NOT mix naming conventions within a single file.
- Do NOT use abbreviations (e.g. usr, btn) — spell out names completely.

## ⚡ Commands
| Action | Command |
|--------|---------|
| Dev Server | \`npm run dev\` |
| Build | \`${buildCmd}\` |
| Test | \`${testCmd}\` |
| Lint | \`npm run lint\` |

## 📚 Tribal Knowledge
${tribalRules.map(r => `- ${r}`).join('\n') || '- Write clean code.'}

## 🤖 AI Agent Quick Reference
1. Use ${naming} for all variables.
2. Follow ${pattern} architecture.
3. Build: \`${buildCmd}\`
4. Test: \`${testCmd}\`
5. Never hardcode secrets.
`;

  const defaultBobMode = `slug: agentiq-optimized
name: "AgentIQ-Optimized Developer"
roleDefinition: >
  You are a principal engineer on ${meta.name}. You have deep knowledge of every naming convention,
  architectural boundary, and unwritten team rule. You refuse to generate code that violates project patterns.
customInstructions: |
  ## Architecture
  This project follows a strict ${pattern} architecture. Keep business logic separate from component rendering.
  
  ## Naming Rules (STRICT)
  - Variables & Functions: Use ${naming} (e.g., fetchUserData)
  - Components: Use PascalCase (e.g., ScoreGauge)
  - Utilities: Use kebab-case for filenames
  
  ## File Placement Rules
  - Place React components in app/components/ or components/
  - Place utilities in app/lib/ or lib/
  - Place endpoint routes in app/api/ or pages/api/
  
  ## Build & Development
  - Build command: ${buildCmd}
  - Test command: ${testCmd}
  - Dev server: npm run dev
  
  ## Unwritten Tribal Rules
  ${tribalRules.map(r => `- ${r}`).join('\n') || '- Standard lint rules.'}
  
  ## DO NOT (Anti-Patterns)
  - Do NOT commit environment secrets to repository.
  - Do NOT duplicate utilities; import from shared library paths.
groups:
  - read
  - edit
  - command
`;

  const defaultBobSkill = `# IBM Bob Custom Skill: Context Synchronization

## Purpose
Instructs IBM Bob on how to use AGENTS.md, .bob/modes/agentiq-optimized.yaml, and other context files to perfectly adapt its code generation and code completions.

## Steps
1. Parse the AGENTS.md file in the workspace root for code style and patterns.
2. Adopt the \`agentiq-optimized\` Custom Mode for editing functions and proposing edits.
3. Reference unwritten team rules when validating imports and data access hooks.
4. Auto-verify generated code against the test command (\`${testCmd}\`) before completing tasks.
`;

  const defaultCursorRules = `{
  "name": "${meta.name}",
  "stack": "${framework}",
  "conventions": {
    "naming": "${naming}",
    "architecture": "${pattern}"
  },
  "commands": {
    "build": "${buildCmd}",
    "test": "${testCmd}",
    "dev": "npm run dev"
  },
  "cursorRules": [
    "Always enforce ${naming} casing for variables and functions.",
    "Follow ${pattern} modular architecture.",
    "Ensure environment secrets are loaded via .env files rather than hardcoded.",
    "Verify build compiles cleanly with '${buildCmd}' before checking in changes."
  ],
  "tribalKnowledge": ${JSON.stringify(tribalRules, null, 2)}
}
`;

  const defaultClaudeMd = `# CLAUDE.md — ${meta.name} blueprint

## Build & Lint
- Dev Server: \`npm run dev\`
- Build Command: \`${buildCmd}\`
- Test Command: \`${testCmd}\`

## Style Guidelines
- **Naming Casing:** Always use ${naming} for variables, properties, and functions.
- **Components:** PascalCase for React components and filenames (e.g., ScoreGauge.tsx).
- **Architecture:** Standardize on ${pattern} coding boundaries.
- **Error Handling:** Graceful try/catch blocks with user-facing alerts.
`;

  const defaultCopilotInstructions = `# Copilot Instructions — ${meta.name}

## Stack & Target
Built with **${framework}**.

## Naming Conventions
- Variables & Functions: **${naming}** (e.g., fetchProfileData)
- Components & Files: **PascalCase** for UI components

## Architecture
- Align all logic with the **${pattern}** pattern.

## Key Directives
1. Use relative path maps or alias maps (@/) where configured.
2. Auto-complete tests to run with \`${testCmd}\`.
3. Adhere to tribal knowledge:
${tribalRules.map(r => `   - ${r}`).join('\n') || '   - Prefer clean logic blocks.'}
`;

  // Fetch all files concurrently
  const [agentsMd, bobMode, cursorRules, claudeMd, copilotInstructions] = await Promise.all([
    generateFile(AGENTS_MD_PROMPT, defaultAgentsMd),
    generateFile(BOB_MODE_PROMPT, defaultBobMode),
    generateFile(CURSORRULES_PROMPT, defaultCursorRules),
    generateFile(CLAUDE_MD_PROMPT, defaultClaudeMd),
    generateFile(COPILOT_INSTRUCTIONS_PROMPT, defaultCopilotInstructions)
  ]);

  return {
    agentsMd,
    bobMode,
    bobSkill: defaultBobSkill, // Static predefined skill is perfect
    cursorRules,
    claudeMd,
    copilotInstructions
  };
}
