import { chat } from './ai-client';
import { 
  AGENTS_MD_PROMPT, 
  BOB_MODE_PROMPT, 
  CURSORRULES_PROMPT, 
  CLAUDE_MD_PROMPT, 
  COPILOT_INSTRUCTIONS_PROMPT 
} from './prompts';
import { RepoMeta, GeneratedFiles } from '../types';

export async function generateContextFiles(
  analysis: any, 
  tribalRules: string[], 
  meta: RepoMeta
): Promise<GeneratedFiles> {
  const analysisStr = JSON.stringify(analysis, null, 2);
  const tribalStr = tribalRules.length > 0 
    ? tribalRules.map((r, i) => `${i + 1}. ${r}`).join('\n')
    : 'No explicit tribal rules found in PR logs. Relying on default framework guidelines.';

  // Helper function to query Granite for a file content with safe fallbacks
  async function generateFile(promptTemplate: string, fallbackContent: string): Promise<string> {
    try {
      const system = "You are a professional software architect. Your goal is to output ONLY the requested file contents without any codeblocks, markdown wrapper tags, or conversational fluff.";
      const user = promptTemplate
        .replace('{analysisJson}', analysisStr)
        .replace('{tribalRules}', tribalStr);
      
      const response = await chat(system, user);
      if (response && response.trim().length > 100) {
        return response.trim();
      }
      return fallbackContent;
    } catch (err) {
      console.warn('Error generating file with Granite, falling back to template:', err);
      return fallbackContent;
    }
  }

  // Pre-generate professional templates for fallbacks
  const framework = analysis.buildDeploy?.framework || 'Next.js';
  const naming = analysis.conventions?.namingPattern || 'camelCase';
  const buildCmd = analysis.buildDeploy?.buildCommand || 'npm run build';
  const testCmd = analysis.buildDeploy?.testCommand || 'npm run test';
  const pattern = analysis.architecture?.pattern || 'Layered';

  const defaultAgentsMd = `# AGENTS.md — Generated by AgentIQ 🧠
# Initial AgentIQ Score: ${analysis.conventions?.score || 30}/100 
# Generated: ${new Date().toLocaleDateString()}

## 🚀 Repository Blueprint
Welcome to **${meta.name}**. This codebase uses **${framework}** and is styled according to the **${naming}** naming pattern. 

## 🏗️ Architectural Pattern
- **Pattern:** ${pattern}
- **Conventions:** ${analysis.conventions?.fileOrganization || 'Standard structure'}

## 🛠️ Essential Development Operations
- **Development Server:** \`npm run dev\`
- **Build Production Bundle:** \`\`\`bash\n${buildCmd}\n\`\`\`
- **Run Test Suite:** \`\`\`bash\n${testCmd}\n\`\`\`

## 📚 Tribal Rules & unwritten guidelines
${tribalRules.map(r => `- ${r}`).join('\n') || '- Always follow DRY principles and write semantic, accessible HTML.'}

## ⛔ Code Anti-patterns
- Do NOT bypass standard state managers or hook interfaces.
- Do NOT hardcode secrets or key tokens (use environment variables).
`;

  const defaultBobMode = `slug: agentiq-optimized
name: "AgentIQ-Optimized Developer"
roleDefinition: >
  You are an expert developer working on ${meta.name}. You follow conventions with extreme discipline.
customInstructions: |
  ## Design system & Style
  Use ${naming} naming scheme for all files, variables, and properties.
  
  ## Build Commands
  - Build command: ${buildCmd}
  - Test command: ${testCmd}

  ## Unwritten code rules
  ${tribalRules.map(r => `- ${r}`).join('\n') || '- Write modular, reusable code.'}
groups:
  - read
  - edit
  - command
`;

  const defaultBobSkill = `# IBM Bob Custom Skill: Context Synchronization

## Purpose
Instructs IBM Bob on how to use AGENTS.md, .bob/modes/agentiq-optimized.yaml, and other context files to perfectly adapt its code generation and code completions.

## Steps
1. Parse the AGENTS.md file in the workspace root for code style and patterns.
2. Adopt the \`agentiq-optimized\` Custom Mode for editing functions and proposing edits.
3. Reference unwritten team rules when validating imports and data access hooks.
4. Auto-verify generated code against the test command (\`${testCmd}\`) before completing tasks.
`;

  const defaultCursorRules = `// .cursorrules for ${meta.name}
// AI instructions for Cursor Editor

const rules = {
  stack: "${framework}",
  conventions: {
    naming: "${naming}",
    architecture: "${pattern}"
  },
  commands: {
    build: "${buildCmd}",
    test: "${testCmd}"
  },
  unwrittenRules: ${JSON.stringify(tribalRules, null, 2)}
};

module.exports = rules;
`;

  const defaultClaudeMd = `# CLAUDE.md — ${meta.name} blueprint

## Build & Lint
- Build command: \`${buildCmd}\`
- Test command: \`${testCmd}\`
- Dev server: \`npm run dev\`

## Style Guidelines
- Use **${naming}** naming patterns for all variables, files, and properties.
- Ensure all business logic complies with the project's **${pattern}** architecture.
- Do NOT expose tokens or client credentials.
`;

  const defaultCopilotInstructions = `# Copilot Instructions — ${meta.name}

## Stack
This repository is built with **${framework}**.

## Naming Conventions
- Always write functions and files using the **${naming}** naming convention.

## Specific Architecture
- Follow the **${pattern}** structure precisely.

## Key Rules
${tribalRules.map(r => `- ${r}`).join('\n') || '- Prefer simple, atomic components and utility helper functions.'}
`;

  // Fetch all files concurrently
  const [agentsMd, bobMode, cursorRules, claudeMd, copilotInstructions] = await Promise.all([
    generateFile(AGENTS_MD_PROMPT, defaultAgentsMd),
    generateFile(BOB_MODE_PROMPT, defaultBobMode),
    generateFile(CURSORRULES_PROMPT, defaultCursorRules),
    generateFile(CLAUDE_MD_PROMPT, defaultClaudeMd),
    generateFile(COPILOT_INSTRUCTIONS_PROMPT, defaultCopilotInstructions)
  ]);

  return {
    agentsMd,
    bobMode,
    bobSkill: defaultBobSkill, // Static predefined skill is perfect
    cursorRules,
    claudeMd,
    copilotInstructions
  };
}
